using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BLL
{
    public enum enumtinh
    {
        CA_NUOC = 0,
        DONG_BANG_SONG_HONG = 1,
        HA_NOI = 2,
        VINH_PHUC = 3,
        BAC_NINH = 4,
        QUANG_NINH = 5,
        HAI_DUONG = 6,
        HAI_PHONG = 7,
        HUNG_YEN = 8,
        THAI_BINH = 9,
        HA_NAM = 10,
        NAM_DINH = 11,
        NINH_BINH = 12,
        TRUNG_DU_VA_MIEN_NUI_PHIA_BAC = 13,
        HA_GIANG = 14,
        CAO_BANG = 15,
        BAC_KAN = 16,
        TUYEN_QUANG = 17,
        LAO_CAI = 18,
        YEN_BAI = 19,
        THAI_NGUYEN = 20,
        LANG_SON = 21,
        BAC_GIANG = 22,
        PHU_THO = 23,
        DIEN_BIEN = 24,
        LAI_CHAU = 25,
        SON_LA = 26,
        HOA_BINH = 27,
        BAC_TRUNG_BO_VA_DUYEN_HAI_MIEN_TRUNG = 28,
        THANH_HOA = 29,
        NGHE_AN = 30,
        HA_TINH = 31,
        QUANG_BINH = 32,
        QUANG_TRI = 33,
        THUA_THIEN_HUE = 34,
        DA_NANG = 35,
        QUANG_NAM = 36,
        QUANG_NGAI = 37,
        BINH_DINH = 38,
        PHU_YEN = 39,
        KHANH_HOA = 40,
        NINH_THUAN = 41,
        BINH_THUAN = 42,
        TAY_NGUYEN = 43,
        KON_TUM = 44,
        GIA_LAI = 45,
        DAK_LAK = 46,
        DAK_NONG = 47,
        LAM_DONG = 48,
        DONG_NAM_BO = 49,
        BINH_PHUOC = 50,
        TAY_NINH = 51,
        BINH_DUONG = 52,
        DONG_NAI = 53,
        BA_RIA__VUNG_TAU = 54,
        HO_CHI_MINH = 55,
        DONG_BANG_SONG_CUU_LONG = 56,
        LONG_AN = 57,
        TIEN_GIANG = 58,
        BEN_TRE = 59,
        TRA_VINH = 60,
        VINH_LONG = 61,
        DONG_THAP = 62,
        AN_GIANG = 63,
        KIEN_GIANG = 64,
        CAN_THO = 65,
        HAU_GIANG = 66,
        SOC_TRANG = 67,
        BAC_LIEU = 68,
        CA_MAU = 69
    }
}
