//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillImport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillImport()
        {
            this.BillImportDetails = new HashSet<BillImportDetails>();
        }
    
        public int BillImportId { get; set; }
        public Nullable<int> NhaSXId { get; set; }
        public Nullable<double> BillPay { get; set; }
        public System.DateTime BillImportDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillImportDetails> BillImportDetails { get; set; }
        public virtual NhaSX NhaSX { get; set; }
    }
}
