//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        public int BonusId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<double> TotalMoney { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> BonusDate { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
