//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.BillExport = new HashSet<BillExport>();
            this.Receipts = new HashSet<Receipts>();
            this.chietkhausp = new HashSet<chietkhausp>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerFullName { get; set; }
        public Nullable<System.DateTime> Ngaydk { get; set; }
        public Nullable<int> Isdailycap2 { get; set; }
        public string CustomerWard { get; set; }
        public string CustomerDistrict { get; set; }
        public string CustomerCity { get; set; }
        public Nullable<int> CustomerDiscount { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public string CustomerEmail { get; set; }
        public Nullable<int> CustomerPoint { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillExport> BillExport { get; set; }
        public virtual districts districts { get; set; }
        public virtual provinces provinces { get; set; }
        public virtual wards wards { get; set; }
        public virtual wards wards1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipts> Receipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chietkhausp> chietkhausp { get; set; }
    }
}
