//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaSX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaSX()
        {
            this.BillImport = new HashSet<BillImport>();
            this.product = new HashSet<product>();
            this.Payment = new HashSet<Payment>();
        }
    
        public int NhaSXId { get; set; }
        public string NhaSXName { get; set; }
        public string NhaSXSDT { get; set; }
        public string NhaSXEmail { get; set; }
        public string NhaSXWard { get; set; }
        public string NhaSXDistrict { get; set; }
        public string NhaSXCity { get; set; }
        public Nullable<double> NhaSXChietkhau { get; set; }
        public Nullable<System.DateTime> NhaSXDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillImport> BillImport { get; set; }
        public virtual districts districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> product { get; set; }
        public virtual provinces provinces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual wards wards { get; set; }
    }
}
