//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public Nullable<int> NhaSXId { get; set; }
        public Nullable<double> TotalMoney { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual NhaSX NhaSX { get; set; }
    }
}
